language: node_js
node_js:
  - stable

branches:
  only:
    - main

cache:
  directory:
    - node_modules/

scripts:
  # Run start in the background
  - npm run start &
  - npm run test
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true
